credentials:
  usernames:
    Nick:
      name: Nick
      password: '$2b$12$5.HhVjEfMdJmUkDYuMnVVOFnlVV4pOD9W7B64BO7S4mUXxXvBtwqu'

cookie:
  name: xrpl_overlap_auth
  key: some_random_secret_key_12345
  expiry_days: 30

preauthorized:
  emails: []
