credentials:
  usernames:
    nickm76:
      email: nick@example.com
      name: Nick M
      password: 'hashed_password_here'  # gebruik bij voorkeur een gehashte wachtwoordversie

cookie:
  name: xrpl_auth_cookie
  key: some_random_key
  expiry_days: 30
