credentials:
  usernames:
    demo_user:
      name: Demo User
      email: demo@xrplover.com
      password: '$2b$12$5kgMWEFGKTrRlsqGpSn70eJwL4ijy7tPDAuHVLrHcNyaFybZK1Tvy'

cookie:
  name: xrpl_overlap_auth
  key: secretkey123
  expiry_days: 7
