credentials:
  usernames:
    Nick:
      email: nick@example.com
      name: Nick
      password: '$2b$12$A.G.z/XZxHKYc5FyF8CM4uyry5k5zJToL7C/DlP24F3uMk44Kake2'
cookie:
  expiry_days: 30
  key: some_signature_key
  name: xrpl_overlap_login
preauthorized:
  emails:
    - nick@example.com
