credentials:
  usernames:
    admin:
      name: Admin User
      email: admin@xrpltools.io
      password: '$2b$12$5kgMWEFGKTrRlsqGpSn70eJwL4ijy7tPDAuHVLrHcNyaFybZK1Tvy'

cookie:
  name: xrpl_overlap_cookie
  key: xrpl_supersecret_key
  expiry_days: 14
