credentials:
  usernames:
    demo:
      name: Demo User
      password: '$2b$12$Vg3EcV.9tNxy91mbkzXaXeO8MmwEjZ1DLziFa2z/v7gKvhRWWk5gK'  # wachtwoord = demo123

cookie:
  name: xrpl_auth
  key: supersecretkey
  expiry_days: 30
